version: "3.8"
services:
  dev_db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: goxygen
      POSTGRES_DB: goxygen
    ports:
      - 5433:5432 # Changed this line
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql